* Общие правила
** Любые действия сексуального характера должны быть учтены в правилах.

Если они не учтены, то сперва требуется обговорить и оценить. Иначе штраф.

** Все участники ведут учет балов точно, честно и своевременно.

Без накруток в любую сторону чем бы они не были вызваны.

** Балы не кредитуются, не могут быть отрицательными.

Например действие стоит 1 балл, но два модификатора, удешевляющие действия на 1 балл не сделают это действие приносящим баллы. Оно просто станет бесплатным.

** Любые действия перечисленные в правилах не могут быть выполнены без соответствующего списания или начисления балов независимо от мнения участников.
** Определения

Одно занятие сексом - серия действий сексуального характера со стимуляцией половых органов минимум одного из партнеров, отделеное от другой серии минимум часовым перерывом.
Один день - промежуток времени с 5 утра до 5 утра.
Сутки - 24 часа. Например с указанного момента.

* Зарабатывать баллы
** День воздержания cuckold +10

Без мастурбации конечно

** Поездка hotwife к любовнику +40

+10 за каждые полные сутки у него

*** Каждое занятие сексом с любовником +30

Бонус за вагинальный секс без презерватива +30

*** Каждый раз когда любовник кончил
**** На неё +20
**** В рот +40
**** В неё +60

Без презерватива +100

*** Вылизать после +30

Если любовник кончил куда-то на/в hotwife и прошло не много времени и она не успела помыться/почистить зубы (сохранились следы спермы или сильный запах) то вылизать это место/поцеловать в засос.

** Наблюдать за мастурбирующей hotwife +20

При этом конечно cuckold не разрешено трогать себя. Трогать hotwife только так как она разрешит. 
Бонусы: 
Cuckold связан +20
Hotwife делает это тем самым вибратором +30
Hotwife представляет себе любовника/шепчет его имя +10
Hotwife  делает это лёжа или сидя на cuckold +20
Hotwife одета в одежду любовника (футболка/рубашка) +10

** День принудительного воздержания

Hotwife может объявить любой день днём без оргазмов. Cuckold не может купить оргазмы, не может кончить со шлюшкой (и вероятно трахать). В этот день hotwife может дразнить cuckold сколько угодно и это будет приносить ему баллы. 

*** Возбуждает словами  +5

За каждую историю, фантазию, подробность секса с любовником и т.п.

*** Гладит и царапает тело +5
*** Играет с членом
**** Ногой +10
**** Ртом +20
**** Рукой +30
*** Кунилингус +10
** Хорошая фантазия/сон/картиночка cuckold +1

По желанию hotwife

** Селфи hotwife любовнику

Cuckold может попросить увидеть это селфи и тогда теряет баллы.

*** Простое +1
*** Эротическое +5
* Тратить баллы
** Кончить -100

Независимо от способа достижения оргазма

*** На hotwife -150

На выбор hotwife куда именно

*** Hotwife в рот -200
*** В hotwife -300

Без презерватива -600

** Спросить разрешения подрочить -10
** Подрочить без разрешения -40
** Hotwife помогает cuckold мастурбировать
*** Ногой -10
*** Рукой -20
*** Ртом -30
** Трахнуть hotwife
*** На боку -60
*** Сверху -80
*** В разных позах -100
*** Наездница -150
* Модификаторы
** Сутки после возвращения hotwife от любовника -20

Все расходы cuckold на любые действия меньше на 20 баллов. Тоесть попросить подрочить можно вообще бесплатно, а кончить - 80 баллов.

** Сутки перед встречей hotwife с любовником +50

Все расходы cuckold больше на 50 баллов за любое действие. 

** Hotwife одета в одежду (футболка/рубашка) любовника -30

Cuckold получает -30 на одно любое действие за этот секс.

** У cuckold во рту трусики hotwife, испачканные в сперме

Cuckold может выбрать одно любое действие, которое может быть дешевле в этот раз.

*** Своей -10
*** Любовника -30
* Заметки и идеи

Hotwife присылает эротическое селфи, находясь с любовником (из постели/ванной/любовник знает/не знает/это вообще не селфи/присланное не с аккаунта жены).
Игрушки с удалённым управлением.
Каколд трахает Hotwife вибратором.
Можно поиграть на тему надписей на теле


